site_name: Forlight's Docs
repo_url: https://github.com/nlklmll?tab=repositories
#repo_name: nlklmll
nav:
  - Home: index.md

  - 最近:
    - 数据库: MySQL.md


  - 归档: 
    - 计算机系统:
      - Linux系统: linux.md
      - HTTP协议: HTTP.md
    - 数通网络: 
      - IGMP: IGMP.md
    - 网络安全:
      - SQLI: SQL注入.md
      - XSS: XSS注入.md
      - MSF: msf构建木马.md
      - CTFHub WriteUp: CTFHub WriteUp.md
      - DVWA WriteUp: DVWA WriteUp.md
    - 软件: 
      - VMware Pro安装: VMware Pro安装.md
      - typora安装与破解: typora安装与破解.md
  
  
  - About: about.md
theme: 
    name: yeti
    nav_style: dark 
    locale: zh